### ISSUE TITLE
[TASK] New animations collection

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#1007]
## Description
We will create a new collection for the intro and outro animations submitted by users. This animations should be tied to an organization so in the future we can let orgs choose from their submitted intros and outros.

## Related User Story
Include the related User Story #< User Story >

## Objectives
- [ ] Upon user upload of an animation, call the `/add-animation` endpoint that will do the following:
- [ ] Upload to livepeer
- [ ] Get MP4 url from livepeer object
- [ ] Install `@remotion/media-utils@4.0.220` tools
- [ ] Use the `getVideoMetadata()` function from remotion media-utils to obtain essential information about the video
- [ ] Create the object in the animations collection

## Acceptance Criteria
- [ ] The animation object should have this format:

```json
{
  "_id": "ObjectId",
  "label": "intro or outro",
  "type": "media",
  "url": "livepeer mp4 url",
  "sessionId": "",
  "organizationId": "",
  "assetId": "",
  "playbackId": ""
}
```
## Additional Information

![CleanShot 2024-10-14 at 13 16 15](https://github.com/user-attachments/assets/b6e92c14-0fe2-4dad-af19-a05b1bf26c59)

**Comment by Eric-Vondee** [comment]
exclude criteria 4 and 5. @pblvrt  has worked on this.

**Comment by Eric-Vondee** [comment]
```
    {
      id: "test",
      label: "intro or outro",
      type: "media",
      url: "livepeer mp4 url",
     sessionId: "", 
     organizationId: "", 
    assetId: "",
   playbackId: ""
    },
```
