### ISSUE TITLE
[TASK] Be able to drag the whole slider

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#1029]
## Description
I would like to be able to drag around the whole slider

## Objectives
- [ ] Make the whole slider object draggable
- [ ] Update the times of the start and end accordingly

## Acceptance Criteria
- [ ] The playhead should not be affected when dragging

## Additional Information

![CleanShot 2024-10-15 at 15 01 08](https://github.com/user-attachments/assets/a038ba76-848d-44d9-8a57-0bb6b5fff84c)

**Comment by greatsamist** [comment]
The changes have been reverted due to instability while dragging the slider along the timeline, as it tends to jump.
