### ISSUE TITLE
As a Event Org / User, I would add auto-labels and AI Summarisation

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#133]
### User Story:
As an Event Organiser or User, I want an AI program to automatically generate labels and summaries for videos in the StreamETH app. This will enhance search capabilities and provide a tailored suggestion section for each archived video.

### Context:
This feature will build upon an existing repository named [shorten](https://github.com/xvoorvaa/shorten). The repository contains a Python script that utilises [WhisperAI](https://github.com/openai/whisper) to create a text file from the video content. This text file can then be used to generate a summary as well as auto-labels for each video, which are stored in a JSON file.

### How It Works:
1. The video gets processed by WhisperAI to generate a text transcript.
2. The Python script in the "shorten" repo analyses the transcript to generate a summary and identify key topics/labels.
3. The summary and labels are then saved in a JSON file, which is linked to the original video in the StreamETH app.
  
### Acceptance Criteria:
- [x] The system should be able to process a video and generate a text transcript using WhisperAI.
- [x] The generated transcript should be analysed to create both a summary and relevant labels.
- [x] Both the summary and labels should be saved in a Database. The transcription should be saved on Digital Ocean
- [ ] The filter bar should filter globally, not per event.
- [ ] The front-end should show the `aiDescription`
  
### Notes:
- We may need to take a look at Redis or ElesticSearch to index the labels.
- Consider performance implications, as processing videos can be time-consuming.
- Assess the accuracy of the generated labels and summaries.

**Comment by xannyxs** [comment]
This could work with Github Workflow, but we would be reliable to Github again

**Comment by pabloVoorvaart** [comment]
So it think this process should happen in the new server. Its easy for the webhook to trigger an api request I think. 

In regards to the package, it should prob live in av-tools as a standalone script that can be invoked by the server.

**Comment by xannyxs** [comment]
Basic visualization of my plan

https://excalidraw.com/#json=Z6pLY_PY7LzhgXq4JJOVq,bCzfo53RNL5VgcOi3No56g

**Comment by xannyxs** [comment]
An update to this project:

- The webhooks work, and is received from Livepeer.
- The OpenAI API works as well, though it does need improvements.
- Add three colums to MongoDB:
    - A **link** to the transcription text (which is the whole speech-to-text description) `videoTranscription`
    - The summary made by the ai `aiDescription`
    - The labels made by the AI `autoLabels`
