### ISSUE TITLE
As a Event Organiser, I want to have a mainpage for just the organisation

### ISSUE THREAD

**Issue by xvoorvaa** [streamethorg/streameth-platform#161]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Additional context**

**Screenshots**
Do you have an example from another platform, or prototype you made by yourself?

**Comment by pabloVoorvaart** [comment]
This user story has to be well defined before we can merge. Please read this article that explains how to write user stories https://www.atlassian.com/agile/project-management/user-stories

You can also check one of the previous user stories.
