### ISSUE TITLE
[BUG] Data importers should not overwrite files

### ISSUE THREAD

**Issue by wslyvh** [streamethorg/streameth-platform#162]
Currently data importers completely overwrite any JSON files in the repo.
We need to update our importers to check if a file exists.
If so, only write the imported fields. Any existing properties should be remain untouched and part of the files.

Priority on the session JSON files, as we will start writing data to those from the post-production flows as well.
We need to make sure we don't lose any data.

**Comment by pabloVoorvaart** [comment]
fixed and pushed to dev direclty
