### ISSUE TITLE
The Archive menu item should show as soon as session videos are available for the event

### ISSUE THREAD

**Issue by wslyvh** [streamethorg/streameth-platform#167]
AFAIK the archive is currently enabled by flipping the `archiveMode` switch. 
But the archive page should show up as soon as there are sessions with videos (i.e. have a `videoUrl` or `playbackId` property.

**Comment by pabloVoorvaart** [comment]
There could be videos on the archive but the event is still ongoing, for instance in a 3 day event day 1 videos could be up but you still have day 2 and 3 to go. Closing since IMO functionality is correct atm.

**Comment by wslyvh** [comment]
I'm not suggesting to completely close an event. Only to add the archive menu item to the navigation.
With our new post-production pipeline we can push session video even when the livestreams are still active.
Especially for multi-day events we want to push individual session videos ASAP and not wait until an event is over to flip the switch to archive. 

it should be possible to have livestreams + archive active at the same time.

**Comment by pabloVoorvaart** [comment]
should be fixed in dev now, can u check @wslyvh
