### ISSUE TITLE
As a User, I would like to donate to StreamETH (with the help of GiveETH)

### ISSUE THREAD

**Issue by xvoorvaa** [streamethorg/streameth-platform#170]
**Is your feature request related to a problem? Please describe.**
As a user, I would like to see the platform grow and donate to it.

**Describe the solution you'd like**
A simple button that redirects to [GivETH](https://giveth.io/) in the corner of the website should be an straightforward solution

**Comment by pabloVoorvaart** [comment]
I dont think this should be part of the product as of now. We could add this in the readme or the website / twitter. Closing and moving this to notion tasks.
