### ISSUE TITLE
Add an informative README

### ISSUE THREAD

**Issue by xvoorvaa** [streamethorg/streameth-platform#172]
**Is your feature request related to a problem? Please describe.**
I would be great to have a short but clear README about streamETH, and where to find more information

**Comment by pabloVoorvaart** [comment]
I dont think this needs to be a user story but it can be just a task. User stories are feature descriptions for user of the application itself

**Comment by xvoorvaa** [comment]
We're on the track to improve our project documentation and ease the setup process for all new contributors. Here are the key points we're aiming to address:

1. **Website Additions**:
   - We're looking to include `streameth.org` and `app.streameth.org` into our documentation to provide users and contributors with a clearer understanding of our platform's public and app-specific functionalities.

2. **Contribution Guidelines**:
   - A "How to Contribute" section is crucial. This will include details on submitting issues, pull requests, and a code of conduct for contributors.

3. **Documentation Resources**:
   - We'll point to our existing comprehensive documentation and expand upon it, ensuring new users can find detailed information on the platform's features, architecture, and more.

4. **StreamETH-Platform Summary**:
   - A brief overview of what the StreamETH platform is, its primary features, and the problems it aims to solve.

5. **Goals of StreamETH**:
   - Clearly define the objectives and long-term goals of StreamETH, to align the community's efforts and the development trajectory.

6. **Setup Quickstart**:
   - Provide a simplified setup guide, outlining necessary environment variables, system prerequisites, and a step-by-step guide to getting a local development instance up and running.

If anyone has any additional insights or feedback, please feel free to chime in!
