### ISSUE TITLE
[BUG] Archive page is inconsistently ordered

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#264]
**Bug Description**
The stage tag is incorrectly displayed . Specifically, when there's only one stage, the stage tag should not appear. However, it's currently visible even for a single stage, which is misleading.

**Steps to Reproduce**
- Navigate to 'https://app.streameth.org/zuzalu/zuconnect__zk_track/archive'.
- Observe the display of the stage tag on the page.

**Expected Behavior**
- When there is only one stage, the stage tag should be hidden.
- When there are multiple stages, the stage tag should be displayed correctly.

**Actual Behavior**
The stage tag is incorrectly displayed even when there is only one stage.

**Screenshot**
Incorrect Stage Tag Display (The screenshot shows the stage tag being displayed for a single stage)

**Comment by greatsamist** [comment]
We concluded not to display stage on the archive page and we already got a filter for stage.
