### ISSUE TITLE
[BUG]Thumbnails not showing on the archive

### ISSUE THREAD

**Issue by carlotacool** [streamethorg/streameth-platform#268]
Bug Description
Some thumbnails are not showing on the App Archive. 

When speakers make last minute changes to the title of their session, meaning that they do not match the content of the last batch of digital assets, the thumbnails do not show on the app. 

Go to: 
https://app.streameth.org/zuzalu/zuconnect__decentralized_social_track/archive

**Comment by xannyxs** [comment]
We should find a way to create all the thumbnails (if they are missing) when we are building on Vercel? What do you think @greatsamist @pabloVoorvaart?
