### ISSUE TITLE
As a user I want to keep basic event information while exploring the archive

### ISSUE THREAD

**Issue by wslyvh** [streamethorg/streameth-platform#270]
Basic event information is currently only shown on the event overview page. 
![image](https://github.com/streamethorg/streameth-platform/assets/25974464/0cf33d73-8466-4a70-90a4-b8c5b48ab3fe)

Once an event goes to archiveMode - this information is lost an no longer shown.
It would be nice to still display this information on the archive.

We could copy the entire hero section to the archive.
Or maybe add an about/info page

**Comment by pabloVoorvaart** [comment]
Closing and adding it as draft for next sprint

https://github.com/orgs/streamethorg/projects/3/views/2?pane=issue&itemId=46066089
