### ISSUE TITLE
ETHChicago's archive has only two sessions while we have edited many more

### ISSUE THREAD

**Issue by aronpips** [streamethorg/streameth-platform#283]
**Describe the bug**
ETHChicago has only two sessions uploaded while on our drive there are many more edited

**Screenshots**
<img width="1528" alt="Screenshot 2023-11-30 at 12 35 14" src="https://github.com/streamethorg/streameth-platform/assets/123663431/eaeb22d2-5380-42a9-8cfd-c175cdb0ddef">

Available talks : https://drive.google.com/drive/folders/1PTl_gK5OZLSfzd4vy66TKnyNablqgRvW

**Comment by xannyxs** [comment]
This issue is not related to a bug and is independent of the StreamETH application. Consequently, this issue is now closed.
