### ISSUE TITLE
Refractor image storage

### ISSUE THREAD

**Issue by pabloVoorvaart** [streamethorg/streameth-platform#288]
#### **Objective:**
Revamp the current image storage architecture to introduce more flexibility, control, and reliability in handling images across our platform.

#### **Key Tasks:**

1. **API Integration for Image Uploads:**
   - Develop and integrate a new API method to enable seamless image uploads.
   - Ensure robust error handling and support for various image formats.

2. **Admin UI Components for Image Management:**
   - Design and implement interactive UI components within the admin panel.
   - Enable admins to easily modify and manage images associated with events, sessions, and organizations.

3. **Flexible Image Storage Service:**
   - Architect a modular image storage service, easily adaptable to different storage solutions (e.g., cloud, local).
   - Implement a plug-in system to allow quick integration with various storage providers.

4. **Fallback Image Mechanism:**
   - Modify the controller logic to return a default fallback image when no specific image is found.
   - Ensure that this mechanism is smooth and does not impact user experience.

#### **Edge Cases:**

- **Large File Sizes:**
  - Users attempt to upload images significantly larger than the average size. This could impact performance or even cause failures in the upload process.

- **Unsupported File Formats:**
  - Users upload images in formats that are not supported by the system. The system should handle these gracefully, either by converting them to a supported format or providing a clear error message.

- **Simultaneous Access and Modifications:**
  - Multiple admins attempt to modify the same image at the same time in the Admin UI, potentially leading to conflicts or data corruption.

**Comment by xannyxs** [comment]
@pabloVoorvaart Can we close this one?
