### ISSUE TITLE
As a User I want to be able to report content errors

### ISSUE THREAD

**Issue by ligi** [streamethorg/streameth-platform#317]
Recently found an [error in the metadata of some video](https://twitter.com/mr_ligi/status/1735284292115185908) - would be nice to be able to directly report it inside the app to preserve context and have a low barrier to reporting errors.

**Comment by pabloVoorvaart** [comment]
Create a floating button that allows the user to: 

a. send a direct support message. This direct message should go to a telegram channel in streameth grp chat. User should only be allowed to send one message. 
b. points user to github issues so that issuer can open an issue.
