### ISSUE TITLE
As a User I want a better social preview

### ISSUE THREAD

**Issue by ligi** [streamethorg/streameth-platform#327]
Currently the social preview for a talk on streamETH looks like this:

![image](https://github.com/streamethorg/streameth-platform/assets/111600/13972c44-4b80-48be-be0e-ed2d43fe2ca6)

It would be better if it is e.g. the cover image of the talk - but for sure something relevant to the talk that is linked - not something general about the platform.

**Comment by greatsamist** [comment]
This issue has been fixed. 
<img width="604" alt="image" src="https://github.com/streamethorg/streameth-platform/assets/88172184/1db0ea93-592d-4532-bac3-eae170b16225">
