### ISSUE TITLE
As an event organizer, I want to create an account on streameth to manage my organizations and events

### ISSUE THREAD

**Issue by pabloVoorvaart** [streamethorg/streameth-platform#358]
- [x] Generate Admin Auth Token for Api Requests
- [x] Allow users to login from the frontend
- [ ] Allow users to manage events for an organisation

**Comment by ashuydv** [comment]
hey, i would like to contribute here !

**Comment by xannyxs** [comment]
@pabloVoorvaart

Reminder: We will need to update our Privacy Terms of StreamETH once we collect user data. (Even if it is just their Wallet address)

**Comment by ashuydv** [comment]
yes, i can start with that !

**Comment by pabloVoorvaart** [comment]
- [ ] get user profile
- [ ] signout endpoint
- [ ] get current session endpoint 
- [ ] create /session page
- [ ] create AddOrganization component
- [ ] filter out organization row

**Comment by xannyxs** [comment]
Would also be nice to have a user page to change personal settings, like linking your YouTube Channel
