### ISSUE TITLE
As an event organiser, I want to upload a video to my event

### ISSUE THREAD

**Issue by pabloVoorvaart** [streamethorg/streameth-platform#383]
## User Story
As an event organiser, I want to easily upload a video to my event / organisation so that i can store and distribute my content using decentralised infrastructure and other social platform

## Acceptance Criteria
- [ ] Videos will be uploaded to livepeer
- [ ] On video upload, a session will be created via the streameth api. User will have to add the relevant data to the video so that a session can be created.
- [ ] User will be able to follow progress with a progress bar. 

## Mockups & Examples (Optional)
<img width="1440" alt="Screenshot 2024-02-05 at 16 05 30" src="https://github.com/streamethorg/streameth-platform/assets/38107177/5fc4343e-65db-4de9-866a-2053c3e7f3c7">

**Comment by xannyxs** [comment]
I am encountering a few barriers. I think we should utilise the API endpoint `/upload`. Which will trigger a function to upload to Livepeer. The expected payload structure is as follows:

```
Payload: {
    sessionId,
    videoName,
    videoFile
}
```

For a clearer understanding of the upload process, check out this drawing:
![Video Upload Process](https://github.com/streamethorg/streameth-platform/assets/56308735/74d630db-ffb2-4943-ba7e-fb6842768bf1)

## Additional Acceptance Criteria

- [ ] Ability to cancel ongoing uploads, which should be done safely.
- [ ] Support for uploading a thumbnail image alongside the video.
- [ ] Enable uploading to IPFS
- [ ] Implementation of a maximum file size limit, I think 3GB should be the sweet spot.

**Comment by xannyxs** [comment]
![Untitled-2024-02-27-1408 excalidraw](https://github.com/streamethorg/streameth-platform/assets/56308735/e5b6295a-bdde-4e60-afab-cfdd77e3f91b)

https://excalidraw.com/#json=MBX2MwIHm6iAiOJJgwpQN,-B9oOWiWVgJdw2wtUD5LnQ

---

Made an update of the drawing
