### ISSUE TITLE
[BUG] `NavBar` is transparent when hamburger menu shows on a phone

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#402]
**Describe the bug**
When I open the menu on my phone it shows a transparent `NavBar` while the menu is fully white.

**To Reproduce**
1. Go to the homepage
2. Click on the hamburger menu button

**Expected behavior**
The transparency should be turned off when you look at the menu

**Screenshots**
<img width="1092" alt="Screenshot 2024-02-14 at 11 23 32" src="https://github.com/streamethorg/streameth-platform/assets/56308735/6dc14361-c9b1-4392-96d7-5e2f32c95932">

**Comment by pabloVoorvaart** [comment]
not sure if this is a bug or more of a styling suggestion hehe
