### ISSUE TITLE
[BUG] Cant update session

### ISSUE THREAD

**Issue by pabloVoorvaart** [streamethorg/streameth-platform#414]
When updating a session, i get the following error: 

`'slug has "slug" is an excess property and therefore is not allowed'` or 'assetId has "assetId" is an excess property and therefore is not allowed'

How to reproduce: 

make a put request to: https://dev.api.streameth.org/sessions/65cfd0650ccee7775238b890

with the following payload: 

```
{
		"source": {
			"streamUrl": "",
			"start": 0,
			"end": 0
		},
		"playback": {
			"livepeerId": "",
			"videoUrl": "",
			"ipfsHash": "",
			"format": "",
			"duration": 0
		},
		"name": "test 222",
		"description": "test",
		"start": 1708118111408,
		"end": 1708118111408,
		"stageId": "65cf835c00f4aab17c32dd12",
		"speakers": [],
		"videoUrl": "",
		"playbackId": "",
		"assetId": "123",
		"eventId": "65cbcef122a4b757dc13893c",
		"track": [],
		"coverImage": "",
		"slug": "test_222",
		"organizationId": "65cbca1022a4b757dc137876",
		"eventSlug": "",
		"videoTranscription": "",
		"aiDescription": "",
		"autoLabels": []
	}
´´´

**Comment by Eric-Vondee** [comment]
Slug is an excess property because it's been genertated from the backend.  PR https://github.com/streamethorg/streameth-platform/pull/415 fixes the assetId error
