### ISSUE TITLE
[BUG] The video progress bar at the bottom keeps blinking

### ISSUE THREAD

**Issue by aslikaya** [streamethorg/streameth-platform#451]
**Describe the bug**
When I watch a video fullscreen, the video progress bar keeps showing and hiding for a second and showing again - creating a distraction

**To Reproduce**
1. Go to https://streameth.org/watch?event=&session=65d77e4f437a5c85775fef9d
2. Play the video and make it fullscreen
3. See error

**Expected behavior**
Unless the user interacts, the progress bar should be hidden. 

**Screenshots**
Here is the screenshot, the red box is the bar I've been pointing to hide 
<img width="800" alt="Screenshot 2024-02-24 at 18 03 16" src="https://github.com/streamethorg/streameth-platform/assets/9151261/38ca4ae5-8958-4ba7-b2c2-24aa8701feba">

**Desktop (please complete the following information):**
 - Browser [e.g. chrome, safari] Chrome
 - OS: [e.g. iOS] MacOS
 - Version [e.g. 22] *Optional*

**Comment by aslikaya** [comment]
I realized the same problem happens in the other mode (not full screen) when the cursor is placed inside the video

**Comment by pabloVoorvaart** [comment]
thank you for reporting @aslikaya , will fix asap
