### ISSUE TITLE
[BUG] Download button does not showup even though it is enabled

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#453]
**Describe the bug**
When trying to download a video like [this one](https://streameth.org/watch?event=zuzalu_montenegro_2023__cryptoxai&session=65b8f8d6a5b2d09b88ec1936). It does not show up. I checked the Database and it is enabled. Filter on {slug: "zuzalu_montenegro_2023__cryptoxai"}.

**Expected behavior**
There should be a download button.

**Additional context**
Please test if the urI is also correct.

**Comment by greatsamist** [comment]
This particular event does not have an assetId, with our current implementation, assetId is needed to get the download link from Livepeer, if a session does not have an assetId, the download button is hidden.

Possible fix: if a session does not have an assetId but does have a videoUrl, we fetch the mp4 link using the videoUrl from Livepeer

**Comment by xannyxs** [comment]
Good point!

I would suggest to make a script on the backend that we run once to fetch all the assetsIds of the sessions that have a videoUrl. Should take 20 minutes to make
