### ISSUE TITLE
Be able to post videos to Youtube, Farcaster and X

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#632]
Related to #634

**Comment by Mario-SO** [comment]
I created a different issue for each platform

Lens: #706 
Farcaster: #705 
YouTube: #704 
X: #703 

Please @Eric-Vondee, take responsibility on uploading the state of current development of X by checking the checkboxes.
@greatsamist do the same for YouTube.

**Comment by xannyxs** [comment]
Duplicate of #735 #734 #733 #732
