### ISSUE TITLE
Be able to create livestreams on X, farcaster, lens, YouTube

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#636]

**Comment by Mario-SO** [comment]
Is this the multi-stream feature?

**Comment by Mario-SO** [comment]
@greatsamist please answer the previous question and update state of this.

**Comment by greatsamist** [comment]
> Is this the multi-stream feature?

Yes, Users should be able to stream to their linked social destinations.

**Comment by Mario-SO** [comment]
Ok will create separate issues for each, just like for publishing.

**Comment by Mario-SO** [comment]
Closing this one due to creation of #735 #734 #733 and #732
