### ISSUE TITLE
[BUG] Unable to Remove Multistream from Livestream

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#639]
**Describe the bug**
As a user, I am unable to remove a multistream from my livestream (stage). StreamETH does remove it on the front-end, but it does not actually remove it from Livepeer Studio. If the user tries to re-add the stream that was supposedly removed, they will not be able to add the same one again.

**To Reproduce**
1. Go to `http://localhost:3000/studio/test_xanny/livestreams/`
2. Click on a random stream
3. Create a multistream
4. Attempt to remove the multistream
5. Try to re-add the same multistream
6. Repeat the steps until you encounter the error

**Expected behavior**
When a multistream is removed from a livestream, it should be completely removed from both the front-end and Livepeer Studio. The user should be able to re-add the same multistream without any issues.

**Comment by Mario-SO** [comment]
Livepeer support needed
