### ISSUE TITLE
New UX

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#653]
- [x] Missing Delete, Download, Embed & Share button in Edit session page. @greatsamist 
- [x] Few pages misaligned @greatsamist 
- [x] Move 'Change organisation' back to the navbar @xannyxs 
- [x] Homepage should show both the livestreams and asset library. The amount of tables shows is limited to 5 or 6. @greatsamist 
- [x] Add livestream tab @greatsamist 
- [x] Add Destinations to the organization settings @greatsamist 
- [x] Revert Sidebar changes, and make is slimmer / and non-expanded @xannyxs 
- [x] YouTube integration button to Destinations & The stream dashboard @greatsamist 
- [x] Add accordion to the Edit session page. One "publish video" & one "Video data" @greatsamist 
- [x] Add "Manage Stream" button to the Livestream page
- [x] Fix Visibility on edit library form @greatsamist

**Comment by pblvrt** [comment]
There is some ux changes needed: 

- [ ] Button collar hierarchy is incorrect
- [ ] Livestream table had some ui improvements reversed for some reason 
- [ ] Upload video on home page should open the upload modal by default
