### ISSUE TITLE
As a user I want to be able to download the videos

### ISSUE THREAD

**Issue by ligi** [streamethorg/streameth-platform#66]
Just got asked by a presenter of protocol Berlin how to download a video. I think this should be exposed in the UI.

**Comment by xvoorvaa** [comment]
We have thought about this, and this is currently still a discussion internally. We have not added it yet, because of legal reasons.

That said, I am not going to hold you back if you use other methods to download the video.

**Comment by ligi** [comment]
Thanks for the info - wondering what legal reasons there are to not offer the button.

**Comment by xvoorvaa** [comment]
Legally, we need to be cautious about who is able to upload videos and where they're being uploaded to.

Additionally, some events and speakers have restrictions on how their videos can be disseminated. We're looking into coding solutions to manage these permissions more effectively.

**Comment by ligi** [comment]
Thanks for the info!
Wonder if it could be fully event specific - so if the event gives a green light @streamethorg can be in the clear? Or some kind of license the event/speakers release the videos under so @streamethorg cant be in trouble?

**Comment by pabloVoorvaart** [comment]
@greatsamist reopening, I think we should allow users to donwload form all available current and future sources. For instance, if a video is available on ipfs, livepeer and swarm, we should show a modal that allows download from all sources.

**Comment by pabloVoorvaart** [comment]
Also, we should provide the mp4 links for downloads, instead of the hls

**Comment by wslyvh** [comment]
@ligi - MP4 downloads are enabled now for wallet uncon. Thanks to @greatsamist for the fix
https://app.streameth.org/devconnect/wallet_unconference/archive

I'll leave this issue open to track other features as Pablo describes.
IMO we should also allow downloading by default. Only explicitly disable on host's request

**Comment by ligi** [comment]
Nice thanks.
PS: would be nice to add the download attribute:  https://www.w3schools.com/tags/att_a_download.asp

**Comment by pabloVoorvaart** [comment]
Closing for now since baseline requirements are met
