### ISSUE TITLE
[BUG] Images are not shown in organisation page ( in dev ) 

### ISSUE THREAD

**Issue by pblvrt** [streamethorg/streameth-platform#660]
**Describe the bug**
When uploading the cover or the logo for an organisation, uploading works but displaying the images does not

**To Reproduce**
IN DEVELOP
1. Create a new org or go to settings page
2. Upload image and cover image
3. Go to organisation page

**Expected behavior**

**Screenshots**
<img width="1512" alt="Screenshot 2024-06-26 at 10 33 34" src="https://github.com/streamethorg/streameth-platform/assets/38107177/0e5c4fe5-ac08-430a-a067-91db68cc2733">

**Additional context**
I think this is only a bug in develop

**Comment by greatsamist** [comment]
## Root Cause Analysis
This bug was caused by our SPACE_STORAGE_PATH environment variable for development pointing to "streameth-production" instead of "streameth-develop" on Vercel.

## Resolution
I have fixed the environment variable path on Vercel, which resolved this bug.
