### ISSUE TITLE
[BUG] Share modal has wrong url in livestream page

### ISSUE THREAD

**Issue by pblvrt** [streamethorg/streameth-platform#663]
**To Reproduce**
1. Go to to a stream
2. Click on share button
3. try and go to the share link 

**Expected behavior**
The modal should share a link to the right stream url 

**Screenshots**
<img width="1341" alt="Screenshot 2024-06-26 at 10 45 14" src="https://github.com/streamethorg/streameth-platform/assets/38107177/2257861c-b14a-48a8-8e50-a0e490a527b7">

**Comment by Mario-SO** [comment]
isn't it doing it properly? In local I think it is working for me.

![CleanShot 2024-06-26 at 16 08 03](https://github.com/streamethorg/streameth-platform/assets/36546318/3cb31801-36ba-411b-8134-790e2ea20cfb)
