### ISSUE TITLE
[BUG] When clicking an empty stream, better feedback should be provided

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#669]
**Describe the bug**
When creating a livestream but not livestreaming anything, you are redirected to a pretty un-friendly page with a _try again_ button.

**To Reproduce**
1. Go to 'https://streameth.org/< org name >' which must contain an empty livestream
2. Click on the empty livestream.

**Expected behavior**
Either a modal stating that, that livestream is empty, or a better error page, should appear.

**Screenshots**

Org with an empty stream

![CleanShot 2024-06-26 at 11 23 50](https://github.com/streamethorg/streameth-platform/assets/36546318/bc625356-2070-4e70-a94a-f9a676703a94)

When clicking on the empty stream

![CleanShot 2024-06-26 at 11 23 57](https://github.com/streamethorg/streameth-platform/assets/36546318/efca581b-2782-4183-b48a-74627e06e970)

**Comment by pblvrt** [comment]
hmm this should not be happening - will take a look

**Comment by pblvrt** [comment]
@Mario-SO can't reproduce, it seems there was a problem with the api when creating that particular stream, if you create a new one and make it public it works

**Comment by Mario-SO** [comment]
Ok, will close it for now, If I encounter it again, I will reopen.
