### ISSUE TITLE
[BUG] Frequent Playback Stuttering and Reset

### ISSUE THREAD

**Issue by ligi** [streamethorg/streameth-platform#67]
Just watching some videos on streameth and sometimes the video stops.
It goes black and the position-seekbar goes to the start. The only way to recover is to reload the page and find the position again. I cannot remember it from watching videos from ETHBerlin back then - so it might be a regression. But had it watching ProtocolBerg videos now already multiple times.

Seems there is nothing related/helpful in the console
![image](https://github.com/streamethorg/streameth-platform/assets/111600/572d87f5-0820-4b4c-8eee-d2c7a44b41bc)

video of it happening
https://github.com/streamethorg/streameth-platform/assets/111600/b868e468-a812-4e03-bf0f-5291e1345908

It happens in brave and firefox browser

**Comment by xvoorvaa** [comment]
Thanks @ligi! My colleague @pabloVoorvaart is already working on a fix on this issue.

**Comment by ligi** [comment]
any update?

**Comment by pabloVoorvaart** [comment]
hey @ligi thanks for reporting, can reproduce on that last issue so thank you for sharing. Most likely an issue with the livepeer player, will report to them and investigate on my own

**Comment by pabloVoorvaart** [comment]
seems to be fixed, we havent received reports of this happening again
