### ISSUE TITLE
[BUG] Update Banner Image Resolution for Organisation Creation

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#675]
**Describe the bug**
When creating an organisation, the banner upload instructions currently state: "Drag or click to upload image here. Maximum image file size is 20MB. Best resolution of 1584 x 396px. Aspect ratio of 4:1." The specified aspect ratio seems unclear. To simplify, we should change the resolution to 1600 x 400 px, a more rounded number.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `/studio/create`
2. Observe the current banner upload instructions

**Expected behaviour**
Update the banner image resolution to 1600 x 400 px in the instructions.

**Screenshots**
![Screenshot 2024-06-27 at 11 10 10](https://github.com/streamethorg/streameth-platform/assets/56308735/97770c21-c2da-4049-b59a-2751844f73cd)

**Additional context**
We may need to verify the aspect ratio used on the organisation page to ensure consistency.

**Comment by coderight1** [comment]
Hi @xannyxs , want to work on this , please assign.
