### ISSUE TITLE
[BUG] Prevent Scrolling on Studio Homepage When No Content at Bottom

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#677]
**Describe the bug**
The studio homepage allows scrolling even when there is no content at the bottom, which should not occur as it is intended to be a static page.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `/studio/[organizationSlug]`
2. Scroll down
3. Observe the unnecessary scrolling

**Expected behaviour**
Scrolling should be disabled when there is no content at the bottom of the page.

**Screenshots**
[Link to video showing the issue](https://github.com/streamethorg/streameth-platform/assets/56308735/26ac8d68-9594-47b4-85e0-ba3061dc6e5e)

**Comment by Mario-SO** [comment]
The video thingy is great, the thing that it is not so great is that when clicking, it automatically downloads the video to my computer XD, we should provide a link to YT or something idk. (Loom is expensive for this casual usage)
