### ISSUE TITLE
[BUG] Fix Z-Index Issue for Upload Dialog on Video Library Page

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#679]
**Describe the bug**
The `Table Names` of the video library are visible above the upload dialog, making it difficult to upload a video.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `/studio/[organizationSlug]/library`
2. Click on 'Upload video'
3. Observe that the table headers appear above the upload dialog

**Expected behaviour**
The table should be behind the upload dialog on the z-axis.

**Screenshots**
![Screenshot 2024-06-27 at 13 10 53](https://github.com/streamethorg/streameth-platform/assets/56308735/4b7449d6-2937-421d-bba1-3e6a6d0f2ff5)

**Comment by xannyxs** [comment]
Found another one in the `Team members` tab

<img width="1574" alt="Screenshot 2024-06-28 at 11 26 15" src="https://github.com/streamethorg/streameth-platform/assets/56308735/9b141285-a14b-44ef-9b13-98a71de1b168">

**Comment by Mario-SO** [comment]
related to #662
