### ISSUE TITLE
[BUG] Prevent Scheduling Livestreams in the Past

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#680]
**Describe the bug**
Users are currently able to schedule a livestream at a time that has already passed. For example, on 27th June at 13:15, it is possible to schedule a livestream for 12:00. The form shows an error but still allows clicking the 'create livestream' button.

**To Reproduce**
Steps to reproduce the behaviour:
1. Go to `/studio/[organizationSlug]`
2. Schedule a livestream for a past date and time
3. Click 'create livestream'
4. Observe that the livestream is created despite the error

**Expected behaviour**
The livestream should not be created until the user provides a valid future date and time.

**Screenshots**
![Screenshot 2024-06-27 at 13 24 15](https://github.com/streamethorg/streameth-platform/assets/56308735/dd5d6e70-d68d-452c-afc9-5022d2ae9f02)

**Comment by Mario-SO** [comment]
Where have you seen that? The image I provide is in prod.

![Image](https://github.com/streamethorg/streameth-platform/assets/36546318/10572b3c-9156-4a3f-9390-494c82aa7da3)

**Comment by Mario-SO** [comment]
Closing because this is already fixed in prod.
