### ISSUE TITLE
[BUG] Social share images are wrong

### ISSUE THREAD

**Issue by pblvrt** [streamethorg/streameth-platform#702]
**Describe the bug**
When sharing an organisation page, livestream or video, the social share image is wrong, right now its showing our default social image

It should show the organisation page cover image as default or the video / livestream thumbnail 

<img width="450" alt="Screenshot 2024-07-02 at 11 08 53" src="https://github.com/streamethorg/streameth-platform/assets/38107177/570d3fa9-a9e2-4866-806b-3b1a8f54ce91">

**Comment by pblvrt** [comment]
why is this low priority ? Been open for 3 weeks

**Comment by pblvrt** [comment]
Not sure if this was fixed, but social images are still wrong here: 

https://streameth.org/funding_the_commons

**Comment by Mario-SO** [comment]
Talked about in 23/07 daily meeting, this is not wrong, it is the way it works. We look for a thumbnail in three different places and if none of them are set, then the default image is shown.

Will close if no more comments added
