### ISSUE TITLE
[BUG] Upload video on home page should open the upload modal by default

### ISSUE THREAD

**Issue by greatsamist** [streamethorg/streameth-platform#736]
**Describe the bug**

**To Reproduce**
1. Go to studio homepage
2. Click on upload video button
3. It is currently redirecting to the library page

**Expected behavior**
 When you click on the upload video button on the studio homepage,  It should open the upload video modal and not redirect to the library page.

**Screenshots**
<img width="666" alt="image" src="https://github.com/streamethorg/streameth-platform/assets/88172184/ab218469-8459-4655-bb4c-f0a87d83a1a0">

**Comment by pblvrt** [comment]
I agree but its not a bug, more like an improvement @Mario-SO
