### ISSUE TITLE
[BUG] Deadcode in Stream Health Badge Component

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#737]
## Description
The `Badge` component that displays the stream health status contains deadcode, which is causing visual inconsistencies on the stream Dashboard. This deadcode appears alongside the actual health status, creating a confusing user interface.

## Steps to Reproduce
1. Start a live stream
2. Navigate to the stream Dashboard
3. Observe the stream health `Badge` component

## Expected Behavior
The `Badge` component should only display the current health status of the stream, without any additional deadcode or unintended content.

## Screenshot
![Stream Health Badge Issue](https://github.com/streamethorg/streameth-platform/assets/56308735/f8ff276e-3c0a-4213-a8f8-4ea6d237d028)

**Comment by Mario-SO** [comment]
Could you provide photo of the actual code? or maybe name the file where the dead code is found.

**Comment by pblvrt** [comment]
Low hanging fruit that is easy to fix @Mario-SO
