### ISSUE TITLE
[BUG] Unable to Return to Stream Selection from Clipping Page

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#767]
## Description
After selecting an event and stream on the `/studio/clips` page and proceeding to the clipping interface, users are unable to navigate back to the stream selection page. This lack of a return option limits user control and navigation flexibility within the clipping feature.

## Steps to Reproduce
1. Navigate to `/studio/clips`
2. Select an event and stream
3. Attempt to return to the stream selection page

## Expected Behavior
A clearly visible button or navigation option should be present, allowing users to return to the stream selection page from the clipping interface.

## Screenshot
![Clipping Interface Without Return Option](https://github.com/user-attachments/assets/ebf600b4-3159-4cec-b503-748013cb2d18)

**Comment by Mario-SO** [comment]
isnt the home icon in the side bar just that?
