### ISSUE TITLE
I want to see and manage video processing errors

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#775]
**Is your feature request related to a problem? Please describe.**
Currently, when there's an error during video processing, the UI continues to show the video as "processing" indefinitely. This creates two significant issues:

1. Poor User Experience: Users are misled into thinking their video is still being processed when it has actually failed.
2. Inability to Manage Failed Videos: Users can't remove these failed videos from their library, leading to cluttered and confusing video management.

**Describe the solution you'd like**
We need to implement an error handling mechanism for video processing that includes:

1. An `error component` that clearly displays when something has gone wrong during video processing.
2. The ability for users to delete videos that have failed processing from their library.

**Additional context**
- The back-end is already handling these errors and updating the `state` of the video.
- The front-end needs to be updated to reflect these state changes and provide appropriate user interactions.
- This is a follow-up of #769

**Comment by xannyxs** [comment]
```
[streameth-platform-packages-new2] [2024-07-18 21:13:16] Livepeer Payload: {
[streameth-platform-packages-new2] [2024-07-18 21:13:16]   id: '7dc1cb9a-8f45-4d1f-b3b1-25a8641ea2ba',
[streameth-platform-packages-new2] [2024-07-18 21:13:16]   webhookId: '83ab5b2c-a4b0-4644-9285-bf98ac2f725e',
[streameth-platform-packages-new2] [2024-07-18 21:13:16]   createdAt: 1721337195316,
[streameth-platform-packages-new2] [2024-07-18 21:13:16]   timestamp: 1721337196019,
[streameth-platform-packages-new2] [2024-07-18 21:13:16]   event: 'asset.failed',
[streameth-platform-packages-new2] [2024-07-18 21:13:16]   payload: { id: 'def892e4-9732-4a18-9aba-047376a636ea', snapshot: {} }
[streameth-platform-packages-new2] [2024-07-18 21:13:16] }
```

**Comment by Mario-SO** [comment]
Needs rework to better define it

**Comment by Mario-SO** [comment]
Add a processing failed filter -> New issue
