### ISSUE TITLE
[BUG] I am unable to sign in using my gmail. on the signup page using google auth. Just head to signup page and login using google auth and it fails to do so. the reload is quite fast can't upload the pictures. 

### ISSUE THREAD

**Issue by rahulsingh3526** [streamethorg/streameth-platform#779]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Comment by xannyxs** [comment]
Hey @rahulsingh3526 , thanks for the bug report. Do you already have an account, or is this your first time logging onto our service.

**Comment by rahulsingh3526** [comment]
@xannyxs No I am a first time visitor to your website and tried signup for the first time.
