### ISSUE TITLE
[BUG] Remove Axios

### ISSUE THREAD

**Issue by wslyvh** [streamethorg/streameth-platform#79]
**Describe the bug**
Remove the `axios` dependency. 

Next.js uses and extends the default fetch WebAPI by default which should be available on both front-/server side.
If we need anything outside of the Next.js context, I'd suggest something like `cross-fetch` so we can use the same code, APIs, etc. consistently. No need for additional dependencies.

**Comment by xvoorvaa** [comment]
Fixing it on #91
