### ISSUE TITLE
[BUG] Broken images for funding the commons event

### ISSUE THREAD

**Issue by pblvrt** [streamethorg/streameth-platform#796]
All images for funding the commons 2023 are broken, example: 

https://streamethapp.ams3.cdn.digitaloceanspaces.com/sessions/funding_the_commons_berlin_2023/infrastructuring_open_conspiracies.jpg

**Comment by rahulsingh3526** [comment]
Hey I wanted to contribute to this issue but I am not able to clone the repo on my local setup ? how do I do it i tried going through the docs. but say i need privy id local host not working. 
![Screenshot (679)](https://github.com/user-attachments/assets/056a84d3-db94-4644-88b4-8d21e31b3e42)
