### ISSUE TITLE
As a Developer I am not able to clone the repo what is the service account and the service account email is being talked about. 

### ISSUE THREAD

**Issue by rahulsingh3526** [streamethorg/streameth-platform#810]
**Is your feature request related to a problem? Please describe.**
I was told to enter service account and email when I am trying to make a file .env . what values do I put in those two or which website should I head to like google email or some other type of google account ?

**Comment by Mario-SO** [comment]
👋 Hello mate! 

Thank you so much for taking the time to write this issue! 🙏 We truly appreciate your feedback, and I'm excited to share that this topic was actually a key point of discussion in today's daily standup. 🎯

We're fully aware that our repo isn't as user-friendly to clone and contribute to as we'd like it to be. Rest assured, we're actively working on improving this! As a small team, we're constantly juggling between meeting our clients' product needs and maintaining proper open-source practices.

While we can't provide an immediate solution, I want to be transparent that it will take some time before we can offer you (and other potential contributors) a comprehensive guide on this. We're committed to making it happen, though!

Once again, thank you for your valuable input. We hope you'll keep an eye on us as we continue to evolve and improve. Your patience and interest mean the world to us!

Stay tuned for updates, and don't hesitate to reach out if you have any more questions or suggestions. We're all ears!

Happy coding! 💻✨

**Comment by rahulsingh3526** [comment]
Hey man where do I reach out to couldn't really find a place so had to make a issue on github tried twitter but allows only people with premium. went to website could find there as well. went and checked every single top contributer here same issue only people with premium could chat ? did't find any discord link to ask question. If only someone could help me out setting up the project I would really love to contribute however I can thankyou.

**Comment by Mario-SO** [comment]
Sorry mate, we updated the README.md to explain that the current repo is not very developer friendly. Thanks a lot fro showing your interest though, really really appreciate it.

**Comment by rahulsingh3526** [comment]
Cool if need be let me know how I can help also help you make out the docs for developers and make it developer friendly.
