### ISSUE TITLE
[BUG] 'Updated at' should be 'Created at' for video information

### ISSUE THREAD

**Issue by xannyxs** [streamethorg/streameth-platform#869]
**Describe the bug**
In the video information display, the timestamp is currently labeled as "Updated at". This is incorrect and potentially misleading for users. The timestamp should instead show when the video was originally uploaded, not when it was last edited.

**Expected behavior**
The timestamp should be labeled as "Created at" and should display the original upload date and time of the video. This is more useful for users as they typically remember when they uploaded a video, rather than when they last edited its title or description.

**Screenshots**
<img width="436" alt="Screenshot 2024-08-13 at 17 32 33" src="https://github.com/user-attachments/assets/9e40d412-0de5-498a-a4b5-843175973d38">

**Additional context**
This change is important for user experience as it provides more relevant information. Users are more likely to remember and search based on when they uploaded a video, rather than when they last edited its metadata. This aligns with common practices in other video platforms and will improve the intuitiveness of the interface.

**Comment by Mario-SO** [comment]
Clips should have the date of the clip not the session date.
