### ISSUE TITLE
As User I would like to have a dark mode

### ISSUE THREAD

**Issue by xvoorvaa** [streamethorg/streameth-platform#92]
**Is Your Feature Request Related to a Particular Issue? Please Elaborate.**
I often find myself experiencing eye strain when using the platform for extended periods, particularly in well-lit settings.

**What Solution Do You Propose?**
I'd love to see the addition of both a `dim` and `dark` mode to improve visual comfort. Personally, I find a grey-toned dark mode particularly easy on the eyes. 

**Any Additional Suggestions?**
To make the feature user-friendly, perhaps a toggle button could be added to the interface. Alternatively, an icon from the `lucide` icon set could be incorporated that changes its appearance when clicked to indicate the mode switch.

**Comment by pabloVoorvaart** [comment]
Fully deprio until we have completed all features, closing for now
