### ISSUE TITLE
[TASK] Live page rework

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#935]
## Description
The aim of this task is to improve the UX of the Live page, which currently doesn't provide a quick and easy way to go to our main value proposition of content repurpose.

## Objectives
- [ ] Completely rework the right sidebar
- [ ] improve layout of certain components

## Acceptance Criteria
- [ ] From this page, the user should be able to quickly navigate to main parts of the studio platform like editing (WIP) and clipping

## Additional Information

If the livestream is ongoing, show the clip button to quickly jump to the live clipping

![CleanShot 2024-09-05 at 22 09 02](https://github.com/user-attachments/assets/c531bcd7-b415-43e0-a4f9-085d6f6220db)

There should be two tabs in the sidebar, one for multistream destinations and other for clips from that particular stage

Instead of having such a huge button for editing the title and description of the live, have a new functionality where you can see all clips created from that particular stage, move the edit livestream to a small button just blow the player

![CleanShot 2024-09-05 at 22 03 12](https://github.com/user-attachments/assets/f9004645-244f-4a88-9b0c-6759443d6c2b)

The destinations tab can left as is, but just have one button for adding a new destination, and two like we currently have. Once a new destination is added, keep showing the button so the can add another one
![CleanShot 2024-09-05 at 21 59 21](https://github.com/user-attachments/assets/caea0d2e-97bd-4711-8987-41635da4f38d)

For reference 

![CleanShot 2024-09-05 at 22 19 08](https://github.com/user-attachments/assets/951be622-42da-43fe-b43f-3891e7ee7389)

**Comment by greatsamist** [comment]
Page Primary buttons

1. Add Destinations
2. Clip
