### ISSUE TITLE
[BUG] Share dialog in stream page not showing proper URL

### ISSUE THREAD

**Issue by Mario-SO** [streamethorg/streameth-platform#988]
**Describe the bug**
In the stream page, the share dialog shows a wrong sharing url

**To Reproduce**
1. Go to https://streameth.org/studio/org/livestreams/<stageID>
2. Click on share
3. See `undefined` in the url

**Expected behavior**
the correct sharing url should show up

**Screenshots**
![CleanShot 2024-10-01 at 14 09 08](https://github.com/user-attachments/assets/f1a2eccc-a70d-467b-ba46-2cc59078cd8f)

**Additional context**

**Comment by Mario-SO** [comment]
Did we for some reason removed or changed that next env variable?

![CleanShot 2024-10-01 at 14 35 52](https://github.com/user-attachments/assets/2371ecea-04e7-4b89-8642-67f4fd04f4a9)

**Comment by greatsamist** [comment]
I'm not certain about this. @xannyxs worked on it. This is new and I currently cannot confirm if env was added for prod and dev
